### ISSUE TITLE
RFC Cleaner multi symlink supported system

### ISSUE THREAD

**Issue by john681611** [flying-dice/dcs-dropzone-registry#33]
## Problem
Having now attempted to setup multiple mods to be added to the registry its become clear that the current asset system isn't ideal and makes it more complex than needed to be

```yaml
    assets:
      - source: >-
          https://github.com/Auranis/HighDigitSAMs/releases/download/v2.1.0/HighDigitSAMs_v2_1_0.zip/#/HighDigitSAMs_v2_1_0/Mods/tech/HighDigitSAMs
        target: "{{DCS_USER_DIR}}/Mods/tech/HighDigitSAMs"

```
This hash path is horrible and quite confusing. In terms of development, getting that post `#` part of the URL means triggering a new download that can take a while. 

It also doesn't support when a single download containing multiple items that need to be installed independently the OH-6A mod is an example of this needing 3 symlinks to activate from a single download.

In the end, its complex and doesn't scale and we now have the base complexity to do something better.

## Proposal
We should separate the download link and unpacking config from the actual symlinks.  Like so:

```yaml
assets:
      - remoteSource: https://github.com/Auranis/HighDigitSAMs/releases/download/v2.1.0/HighDigitSAMs_v2_1_0.zip"
         links: 
              - source: "HighDigitSAMs_v2_1_0/Mods/tech/HighDigitSAMs"
                 target: "{{DCS_USER_DIR}}/Mods/tech/HighDigitSAMs"

```
Note: source is assumed to be in the mod folder.

This allows:
- Easier to read config 
- Multi Symlink from one download support
- Corrections to be made (in prod and when setting up a mod) to the symlinking without re-downloading the whole mod
- Simplifies development of a config (you can now download a mod with the wrong config and then figure out the correct linkings)

I think we should make this change while we have relatively few mods to convert.
